In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Exercise 1

In [2]:
pd.__version__

'1.4.4'

In [3]:
!ls

hw01.ipynb  yellow_tripdata_2023-01.parquet  yellow_tripdata_2023-02.parquet

In [4]:
data_jan = pd.read_parquet('yellow_tripdata_2023-01.parquet', engine='pyarrow')
data_jan.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [5]:
len(data_jan.columns.to_list())

19

In [6]:
data_jan.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'airport_fee'],
      dtype='object')

# Exercise 2

In [8]:
data_jan['duration'] = (data_jan['tpep_dropoff_datetime'] - data_jan['tpep_pickup_datetime'])

In [9]:
data_jan.duration = data_jan.duration.apply(lambda dur: dur.total_seconds() / 60)
data_jan

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN,13.983333
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN,19.450000
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN,24.516667
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN,13.000000
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN,14.400000

In [10]:
data_jan['duration'].std()

42.59435124195458

# Exercise 3

In [11]:
total_records_before_clen = len(data_jan)
data_jan = data_jan[(data_jan['duration'] >= 1) & (data_jan['duration'] <= 60)] 
len(data_jan) / total_records_before_clen

0.9812202822125979

# Exercise 4

In [12]:
train_data = data_jan[['PULocationID', 'DOLocationID']].astype('str')

In [13]:
train_dict = train_data.to_dict(orient='records')
train_dict

[{'PULocationID': '161', 'DOLocationID': '141'},
 {'PULocationID': '43', 'DOLocationID': '237'},
 {'PULocationID': '48', 'DOLocationID': '238'},
 {'PULocationID': '138', 'DOLocationID': '7'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '161', 'DOLocationID': '137'},
 {'PULocationID': '239', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '200'},
 {'PULocationID': '164', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '234', 'DOLocationID': '68'},
 {'PULocationID': '79', 'DOLocationID': '264'},
 {'PULocationID': '164', 'DOLocationID': '143'},
 {'PULocationID': '138', 'DOLocationID': '33'},
 {'PULocationID': '33', 'DOLocationID': '61'},
 {'PULocationID': '79', 'DOLocationID': '186'},
 {'PULocationID': '90', 'DOLocationID': '48'},
 {'PULocationID': '113', 'DOLocationID': '255'},
 {'PULocationID': '237', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '229'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '132', 'DOLocationID': '116'},
 {'PULocationID': '163', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '161', 'DOLocationID': '87'},
 {'PULocationID': '68', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '232'},
 {'PULocationID': '43', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '229'},
 {'PULocationID': '170', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '36'},
 {'PULocationID': '163', 'DOLocationID': '186'},
 {'PULocationID': '161', 'DOLocationID': '107'},
 {'PULocationID': '233', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '144', 'DOLocationID': '140'},
 {'PULocationID': '229', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '231'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '170', 'DOLocationID': '43'},
 {'PULocationID': '43', 'DOLocationID': '233'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '162'},
 {'PULocationID': '229', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '224'},
 {'PULocationID': '224', 'DOLocationID': '68'},
 {'PULocationID': '132', 'DOLocationID': '61'},
 {'PULocationID': '236', 'DOLocationID': '236'},
 {'PULocationID': '142', 'DOLocationID': '170'},
 {'PULocationID': '107', 'DOLocationID': '145'},
 {'PULocationID': '164', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '140'},
 {'PULocationID': '43', 'DOLocationID': '125'},
 {'PULocationID': '142', 'DOLocationID': '24'},
 {'PULocationID': '151', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '239'},
 {'PULocationID': '68', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '114'},
 {'PULocationID': '163', 'DOLocationID': '225'},
 {'PULocationID': '137', 'DOLocationID': '236'},
 {'PULocationID': '239', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '158'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '238', 'DOLocationID': '42'},
 {'PULocationID': '107', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '158'},
 {'PULocationID': '238', 'DOLocationID': '238'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '48'},
 {'PULocationID': '141', 'DOLocationID': '140'},
 {'PULocationID': '43', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '261'},
 {'PULocationID': '79', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '232'},
 {'PULocationID': '68', 'DOLocationID': '13'},
 {'PULocationID': '13', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '50'},
 {'PULocationID': '238', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '133'},
 {'PULocationID': '132', 'DOLocationID': '188'},
 {'PULocationID': '132', 'DOLocationID': '149'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '138', 'DOLocationID': '95'},
 {'PULocationID': '132', 'DOLocationID': '218'},
 {'PULocationID': '264', 'DOLocationID': '186'},
 {'PULocationID': '264', 'DOLocationID': '114'},
 {'PULocationID': '264', 'DOLocationID': '79'},
 {'PULocationID': '264', 'DOLocationID': '239'},
 {'PULocationID': '43', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '261'},
 {'PULocationID': '237', 'DOLocationID': '234'},
 {'PULocationID': '90', 'DOLocationID': '48'},
 {'PULocationID': '125', 'DOLocationID': '231'},
 {'PULocationID': '125', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '238'},
 {'PULocationID': '161', 'DOLocationID': '228'},
 {'PULocationID': '186', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '233'},
 {'PULocationID': '162', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '137'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '264', 'DOLocationID': '137'},
 {'PULocationID': '137', 'DOLocationID': '212'},
 {'PULocationID': '141', 'DOLocationID': '231'},
 {'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '79'},
 {'PULocationID': '229', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '144'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '166'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '137'},
 {'PULocationID': '233', 'DOLocationID': '137'},
 {'PULocationID': '170', 'DOLocationID': '238'},
 {'PULocationID': '233', 'DOLocationID': '229'},
 {'PULocationID': '233', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '164'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '7'},
 {'PULocationID': '158', 'DOLocationID': '229'},
 {'PULocationID': '236', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '75'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '79', 'DOLocationID': '234'},
 {'PULocationID': '186', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '112'},
 {'PULocationID': '249', 'DOLocationID': '239'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '75'},
 {'PULocationID': '234', 'DOLocationID': '186'},
 {'PULocationID': '246', 'DOLocationID': '13'},
 {'PULocationID': '234', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '90'},
 {'PULocationID': '107', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '4', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '141', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '43'},
 {'PULocationID': '43', 'DOLocationID': '48'},
 {'PULocationID': '229', 'DOLocationID': '236'},
 {'PULocationID': '43', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '143', 'DOLocationID': '68'},
 {'PULocationID': '132', 'DOLocationID': '25'},
 {'PULocationID': '132', 'DOLocationID': '140'},
 {'PULocationID': '141', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '239'},
 {'PULocationID': '148', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '239'},
 {'PULocationID': '107', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '249'},
 {'PULocationID': '164', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '90'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '234'},
 {'PULocationID': '90', 'DOLocationID': '170'},
 {'PULocationID': '162', 'DOLocationID': '170'},
 {'PULocationID': '142', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '151'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '33'},
 {'PULocationID': '186', 'DOLocationID': '97'},
 {'PULocationID': '236', 'DOLocationID': '137'},
 {'PULocationID': '107', 'DOLocationID': '162'},
 {'PULocationID': '162', 'DOLocationID': '141'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '232'},
 {'PULocationID': '148', 'DOLocationID': '170'},
 {'PULocationID': '137', 'DOLocationID': '13'},
 {'PULocationID': '170', 'DOLocationID': '113'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '148'},
 {'PULocationID': '79', 'DOLocationID': '161'},
 {'PULocationID': '234', 'DOLocationID': '125'},
 {'PULocationID': '211', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '45'},
 {'PULocationID': '231', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '229'},
 {'PULocationID': '162', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '75'},
 {'PULocationID': '43', 'DOLocationID': '48'},
 {'PULocationID': '132', 'DOLocationID': '91'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '48', 'DOLocationID': '246'},
 {'PULocationID': '246', 'DOLocationID': '114'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '132', 'DOLocationID': '265'},
 {'PULocationID': '90', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '48'},
 {'PULocationID': '186', 'DOLocationID': '186'},
 {'PULocationID': '186', 'DOLocationID': '125'},
 {'PULocationID': '125', 'DOLocationID': '97'},
 {'PULocationID': '144', 'DOLocationID': '50'},
 {'PULocationID': '211', 'DOLocationID': '88'},
 {'PULocationID': '87', 'DOLocationID': '13'},
 {'PULocationID': '13', 'DOLocationID': '48'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '142', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '249'},
 {'PULocationID': '158', 'DOLocationID': '48'},
 {'PULocationID': '132', 'DOLocationID': '256'},
 {'PULocationID': '50', 'DOLocationID': '68'},
 {'PULocationID': '114', 'DOLocationID': '239'},
 {'PULocationID': '43', 'DOLocationID': '24'},
 {'PULocationID': '24', 'DOLocationID': '243'},
 {'PULocationID': '137', 'DOLocationID': '141'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '41'},
 {'PULocationID': '239', 'DOLocationID': '42'},
 {'PULocationID': '41', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '48'},
 {'PULocationID': '114', 'DOLocationID': '68'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '237', 'DOLocationID': '143'},
 {'PULocationID': '239', 'DOLocationID': '107'},
 {'PULocationID': '186', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '42'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '246', 'DOLocationID': '233'},
 {'PULocationID': '249', 'DOLocationID': '48'},
 {'PULocationID': '246', 'DOLocationID': '61'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '142'},
 {'PULocationID': '161', 'DOLocationID': '229'},
 {'PULocationID': '164', 'DOLocationID': '234'},
 {'PULocationID': '113', 'DOLocationID': '238'},
 {'PULocationID': '142', 'DOLocationID': '41'},
 {'PULocationID': '151', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '114'},
 {'PULocationID': '50', 'DOLocationID': '48'},
 {'PULocationID': '137', 'DOLocationID': '162'},
 {'PULocationID': '233', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '193'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '79'},
 {'PULocationID': '90', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '148'},
 {'PULocationID': '142', 'DOLocationID': '181'},
 {'PULocationID': '25', 'DOLocationID': '257'},
 {'PULocationID': '164', 'DOLocationID': '90'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '13'},
 {'PULocationID': '170', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '94'},
 {'PULocationID': '132', 'DOLocationID': '80'},
 {'PULocationID': '107', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '107'},
 {'PULocationID': '170', 'DOLocationID': '195'},
 {'PULocationID': '132', 'DOLocationID': '238'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '237'},
 {'PULocationID': '107', 'DOLocationID': '50'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '231'},
 {'PULocationID': '50', 'DOLocationID': '261'},
 {'PULocationID': '249', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '87'},
 {'PULocationID': '132', 'DOLocationID': '10'},
 {'PULocationID': '234', 'DOLocationID': '87'},
 {'PULocationID': '211', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '255'},
 {'PULocationID': '132', 'DOLocationID': '95'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '170', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '79', 'DOLocationID': '236'},
 {'PULocationID': '144', 'DOLocationID': '42'},
 {'PULocationID': '238', 'DOLocationID': '167'},
 {'PULocationID': '238', 'DOLocationID': '167'},
 {'PULocationID': '234', 'DOLocationID': '231'},
 {'PULocationID': '144', 'DOLocationID': '263'},
 {'PULocationID': '161', 'DOLocationID': '127'},
 {'PULocationID': '74', 'DOLocationID': '248'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '238'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '249'},
 {'PULocationID': '48', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '162'},
 {'PULocationID': '141', 'DOLocationID': '89'},
 {'PULocationID': '43', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '138', 'DOLocationID': '74'},
 {'PULocationID': '263', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '151'},
 {'PULocationID': '229', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '229'},
 {'PULocationID': '141', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '263', 'DOLocationID': '145'},
 {'PULocationID': '234', 'DOLocationID': '164'},
 {'PULocationID': '107', 'DOLocationID': '186'},
 {'PULocationID': '238', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '107'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '233', 'DOLocationID': '74'},
 {'PULocationID': '263', 'DOLocationID': '233'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '140'},
 {'PULocationID': '237', 'DOLocationID': '161'},
 {'PULocationID': '229', 'DOLocationID': '137'},
 {'PULocationID': '233', 'DOLocationID': '223'},
 {'PULocationID': '143', 'DOLocationID': '166'},
 {'PULocationID': '24', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '141'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '140', 'DOLocationID': '47'},
 {'PULocationID': '163', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '249', 'DOLocationID': '233'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '141'},
 {'PULocationID': '264', 'DOLocationID': '263'},
 {'PULocationID': '137', 'DOLocationID': '263'},
 {'PULocationID': '162', 'DOLocationID': '140'},
 {'PULocationID': '164', 'DOLocationID': '229'},
 {'PULocationID': '246', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '246'},
 {'PULocationID': '246', 'DOLocationID': '68'},
 {'PULocationID': '246', 'DOLocationID': '4'},
 {'PULocationID': '246', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '137'},
 {'PULocationID': '170', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '140'},
 {'PULocationID': '263', 'DOLocationID': '162'},
 {'PULocationID': '249', 'DOLocationID': '223'},
 {'PULocationID': '146', 'DOLocationID': '145'},
 {'PULocationID': '142', 'DOLocationID': '229'},
 {'PULocationID': '140', 'DOLocationID': '40'},
 {'PULocationID': '231', 'DOLocationID': '164'},
 {'PULocationID': '50', 'DOLocationID': '186'},
 {'PULocationID': '186', 'DOLocationID': '164'},
 {'PULocationID': '170', 'DOLocationID': '237'},
 {'PULocationID': '142', 'DOLocationID': '107'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '50', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '263'},
 {'PULocationID': '166', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '143'},
 {'PULocationID': '234', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '140'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '113', 'DOLocationID': '202'},
 {'PULocationID': '237', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},

In [14]:
dv = DictVectorizer()
X_train = dv.fit_transform(train_dict)

y_train = data_jan['duration'].values

In [15]:
X_train.toarray().shape

(3009173, 515)

# Exercise 5

In [16]:
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_train)

y_pred

array([11.52716243, 10.89764178, 11.32567744, ..., 11.73762391,
       12.70526433, 11.54241824])

In [17]:
mean_squared_error(y_train, y_pred, squared=False)

7.649261822035489

# Exercise 6

In [18]:
data_feb = pd.read_parquet('yellow_tripdata_2023-02.parquet', engine='pyarrow')
data_feb

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-02-01 00:32:53,2023-02-01 00:34:34,2.0,0.30,1.0,N,142,163,2,4.40,3.50,0.5,0.00,0.0,1.0,9.40,2.5,0.00
1,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,-3.00,-1.00,-0.5,0.00,0.0,-1.0,-5.50,0.0,0.00
2,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,3.00,1.00,0.5,0.00,0.0,1.0,5.50,0.0,0.00
3,1,2023-02-01 00:29:33,2023-02-01 01:01:38,0.0,18.80,1.0,N,132,26,1,70.90,2.25,0.5,0.00,0.0,1.0,74.65,0.0,1.25
4,2,2023-02-01 00:12:28,2023-02-01 00:25:46,1.0,3.22,1.0,N,161,145,1,17.00,1.00,0.5,3.30,0.0,1.0,25.30,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913950,2,2023-02-28 23:46:00,2023-03-01 00:05:00,NaN,4.65,NaN,None,249,140,0,20.22,0.00,0.5,4.84,0.0,1.0,29.06,NaN,NaN
2913951,2,2023-02-28 23:26:02,2023-02-28 23:37:10,NaN,2.47,NaN,None,186,79,0,13.66,0.00,0.5,2.65,0.0,1.0,20.31,NaN,NaN
2913952,2,2023-02-28 23:24:00,2023-02-28 23:38:00,NaN,3.49,NaN,None,158,143,0,17.64,0.00,0.5,0.00,0.0,1.0,21.64,NaN,NaN
2913953,2,2023-02-28 23:03:00,2023-02-28 23:10:00,NaN,2.13,NaN,None,79,162,0,13.56,0.00,0.5,2.63,0.0,1.0,20.19,NaN,NaN
2913954,2,2023-02-28 23:03:03,2023-02-28 23:12:51,NaN,2.28,NaN,None,161,140,0,14.89,0.00,0.5,3.78,0.0,1.0,22.67,NaN,NaN

In [19]:
data_feb['duration'] = (data_feb['tpep_dropoff_datetime'] - data_feb['tpep_pickup_datetime'])

In [20]:
data_feb.duration = data_feb.duration.apply(lambda dur: dur.total_seconds() / 60)
data_feb

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,duration
0,1,2023-02-01 00:32:53,2023-02-01 00:34:34,2.0,0.30,1.0,N,142,163,2,4.40,3.50,0.5,0.00,0.0,1.0,9.40,2.5,0.00,1.683333
1,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,-3.00,-1.00,-0.5,0.00,0.0,-1.0,-5.50,0.0,0.00,0.233333
2,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,3.00,1.00,0.5,0.00,0.0,1.0,5.50,0.0,0.00,0.233333
3,1,2023-02-01 00:29:33,2023-02-01 01:01:38,0.0,18.80,1.0,N,132,26,1,70.90,2.25,0.5,0.00,0.0,1.0,74.65,0.0,1.25,32.083333
4,2,2023-02-01 00:12:28,2023-02-01 00:25:46,1.0,3.22,1.0,N,161,145,1,17.00,1.00,0.5,3.30,0.0,1.0,25.30,2.5,0.00,13.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913950,2,2023-02-28 23:46:00,2023-03-01 00:05:00,NaN,4.65,NaN,None,249,140,0,20.22,0.00,0.5,4.84,0.0,1.0,29.06,NaN,NaN,19.000000
2913951,2,2023-02-28 23:26:02,2023-02-28 23:37:10,NaN,2.47,NaN,None,186,79,0,13.66,0.00,0.5,2.65,0.0,1.0,20.31,NaN,NaN,11.133333
2913952,2,2023-02-28 23:24:00,2023-02-28 23:38:00,NaN,3.49,NaN,None,158,143,0,17.64,0.00,0.5,0.00,0.0,1.0,21.64,NaN,NaN,14.000000
2913953,2,2023-02-28 23:03:00,2023-02-28 23:10:00,NaN,2.13,NaN,None,79,162,0,13.56,0.00,0.5,2.63,0.0,1.0,20.19,NaN,NaN,7.000000
2913954,2,2023-02-28 23:03:03,2023-02-28 23:12:51,NaN,2.28,NaN,None,161,140,0,14.89,0.00,0.5,3.78,0.0,1.0,22.67,NaN,NaN,9.800000

In [21]:
data_feb = data_feb[(data_feb['duration'] >= 1) & (data_feb['duration'] <= 60)] 

val_data = data_feb[['PULocationID', 'DOLocationID']].astype('str')
val_dict = val_data.to_dict(orient='records')

X_val = dv.transform(val_dict)

In [22]:
y_val = data_feb['duration'].values

y_pred_val = lr.predict(X_val)

In [23]:
mean_squared_error(y_val, y_pred_val, squared=False)

7.811821332387183